#!/bin/sh

VERSION='master'

WGET=`which wget`

DIST="menv-$VERSION.tar.gz" 
SRC="https://github.com/seanwoods/menv/tarball/$VERSION"
TMP="/tmp"

_PWD=$PWD

check_wget () {
    if [ -z "$WGET" ]; then
        echo "Error. Valid wget not found, required for this operation."
        exit 2
    fi
}

case $1 in
    init)
        check_wget
        cd $TMP && mkdir "menv$$" && cd "menv$$"

        if [ `basename $PWD` != "menv$$" ]; then
            echo "Error: Problem creating temp directory..."
            cd $_PWD
            exit 2
        fi

        wget $SRC -O - | tar -xzv

        if [ $? -ne 0 ]; then
            echo "Error: Problem with wget or tar operation PID $?..."
            cd $_PWD
            exit 2
        fi
        
        if [ `ls | wc -l` -gt 1 ]; then
            echo "Error: Untar resulted in more than one file..."
            cd $_PWD
            exit 2
        else
            newdir=`ls`
        fi
        cd $newdir/skeleton
        
        mv * $_PWD && cd $_PWD
        rm -rf "$TMP/menv$$"

        for dir in routines globals log tmp
        do
            if [ ! -d $dir ]; then
                mkdir $dir
            fi
        done

    ;;
    *)
        if [ ! -f "$PWD/bin/$1" ]; then
            echo "menv: Plugin $1 not found."
            exit 2
        else
            $PWD/bin/$1
        fi
    ;;
esac
